name: Ruby Gem

on:
  push:
    branches:
      - master
    paths:
    - 'lib/soda/version.rb'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Create git tag
      run: |
        version=$(ruby -r ./lib/soda/version.rb -e "print Soda::VERSION")
        url=$(jq .repository.git_refs_url $GITHUB_EVENT_PATH | tr -d '"' | sed 's/{\/sha}//g')
        echo $url

        curl -X POST $url \
          -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"ref\":\"refs/tags/v$version\",\"sha\":\"$GITHUB_SHA\"}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
